name: Docker image test-facing build and push
# Runs tests, then builds and pushes Docker image to Docker Hub if tests passeses
# Uses GitHub Actions secrets for Docker Hub credentials    

on: push

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm test

      # CD starts here (only runs if tests succeed)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push test image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfiles/test.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moussa-jawdat-intro-to-devops-a2:test-latest
