name: ESLint Check

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (auto-fix mode)
        run: |
          npx eslint src --fix || true
          echo "ESLint auto-fix completed"
      
      - name: Generate ESLint report
        run: |
          npx eslint src  > eslint_report.txt || true
          cat eslint_report.txt
